modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/FlyThroughGlass/issues"
license="MIT"

[[mods]]
modId="flythroughglass"
version="${file.jarVersion}"
displayName="Fly Through Glass"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fly-through-glass"
authors="Mrbysco"
description='''
Allows you to fly through glass with an elytra
'''
[[dependencies.flythroughglass]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.flythroughglass]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="flythroughglass.mixins.json"